In [17]:
import pandas as pd
data_dir="/content/drive/MyDrive/Colab/causal_inference-medical/student_performance/StudentsPerformance.csv"
df=pd.read_csv(data_dir, encoding='utf-8')

In [18]:
df.head()

gender     race parental_level_of_education         lunch  \
0  female  group B           bachelor's degree      standard   
1  female  group C                some college      standard   
2  female  group B             master's degree      standard   
3    male  group A          associate's degree  free/reduced   
4    male  group C                some college      standard   

  student_performance  math_score  reading_score  writing_score  
0                none          72             72             74  
1           completed          69             90             88  
2                none          90             95             93  
3                none          47             57             44  
4                none          76             78             75

In [19]:
df.drop(df.columns[[3]], axis=1,inplace=True)
df.gender = df.gender.map({"female":1,"male":0})
df.race = df.race.map({"group A":1,"group B":2,"group C":3,"group D":4,"group E":5})
df['student_performance'] = df['student_performance'].map({"none":1,"completed":0})
df.parental_level_of_education = df.parental_level_of_education.map({"associate's degree":1,"master's degree":2,"bachelor's degree":3,"some college":4,"high school":5,"some high school":6})
df.math_score
#df.test_preparation_course = df.test_preparation_course.map({"completed":1,"none":0})
df.to_csv('StudentsPerformance_processed',index=False,encoding='utf-8_sig')
df.head()

gender  race  parental_level_of_education  student_performance  math_score  \
0       1     2                            3                    1          72   
1       1     3                            4                    0          69   
2       1     2                            2                    1          90   
3       0     1                            1                    1          47   
4       0     3                            4                    1          76   

   reading_score  writing_score  
0             72             74  
1             90             88  
2             95             93  
3             57             44  
4             78             75

### ML Without CI

In [20]:
df.columns = ['gender', 'race', 'parental_level_of_education', 'student_performance', 'math_score', 'reading_score', 'writing_score']
df

gender  race  parental_level_of_education  student_performance  \
0         1     2                            3                    1   
1         1     3                            4                    0   
2         1     2                            2                    1   
3         0     1                            1                    1   
4         0     3                            4                    1   
..      ...   ...                          ...                  ...   
995       1     5                            2                    0   
996       0     3                            5                    1   
997       1     3                            5                    0   
998       1     4                            4                    0   
999       1     4                            4                    1   

     math_score  reading_score  writing_score  
0            72             72             74  
1            69             90             88  
2            90             95             93  
3            47             57             44  
4            76             78             75  
..          ...            ...            ...  
995          88             99             95  
996          62             55             55  
997          59             71             65  
998          68             78             77  
999          77             86             86  

[1000 rows x 7 columns]

In [21]:
y = df.iloc[:, 3]

In [22]:
X = pd.concat([df.iloc[:, :2], df.iloc[:, 3:]], axis=1)

In [23]:
#CLASSIFICATION USING SVM
from sklearn import svm
from sklearn.model_selection import train_test_split

from sklearn import metrics
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)
clf = svm.SVC()
SVM = clf.fit(X_train, y_train)

SVM_y_pred = SVM.predict(X)
print('Accuracy of SVM classifier on test set: {:.2f}'.format(clf.score(X, y)))
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y, SVM_y_pred)
print('\nThe confusion Matrix is : \n',confusion_matrix)
from sklearn.metrics import classification_report
print('\nThe evaluation parameters are : \n',classification_report(y, SVM_y_pred))

Accuracy of SVM classifier on test set: 0.69

The confusion Matrix is : 
 [[ 89 269]
 [ 46 596]]

The evaluation parameters are : 
               precision    recall  f1-score   support

           0       0.66      0.25      0.36       358
           1       0.69      0.93      0.79       642

    accuracy                           0.69      1000
   macro avg       0.67      0.59      0.58      1000
weighted avg       0.68      0.69      0.64      1000



In [24]:
SVM_y_pred

array([1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [25]:
import numpy as np
eff_withoutCI_SVM = np.mean(SVM_y_pred == 1)
print(eff_withoutCI_SVM)

0.865


In [26]:
#CLASSIFICATION USING NAIVE BAYES
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split

from sklearn import metrics
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)
clf = GaussianNB()
NB = clf.fit(X_train, y_train)

NB_y_pred = NB.predict(X)
print('Accuracy of Naive Bayes classifier on test set: {:.2f}'.format(clf.score(X, y)))
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y, NB_y_pred)
print('\nThe confusion Matrix is : \n',confusion_matrix)
from sklearn.metrics import classification_report
print('\nThe evaluation parameters are : \n',classification_report(y, NB_y_pred))

Accuracy of Naive Bayes classifier on test set: 1.00

The confusion Matrix is : 
 [[358   0]
 [  0 642]]

The evaluation parameters are : 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00       358
           1       1.00      1.00      1.00       642

    accuracy                           1.00      1000
   macro avg       1.00      1.00      1.00      1000
weighted avg       1.00      1.00      1.00      1000



In [27]:
NB_y_pred

array([1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0,

In [28]:
#CLASSIFICATION USING RANDOM FOREST
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

from sklearn import metrics
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)
clf = RandomForestClassifier()
RF = clf.fit(X_train, y_train)

RF_y_pred = RF.predict(X)
print('Accuracy of Random Forest classifier on test set: {:.2f}'.format(clf.score(X, y)))
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y, RF_y_pred)
print('\nThe confusion Matrix is : \n',confusion_matrix)
from sklearn.metrics import classification_report
print('\nThe evaluation parameters are : \n',classification_report(y, RF_y_pred))

Accuracy of Random Forest classifier on test set: 1.00

The confusion Matrix is : 
 [[358   0]
 [  0 642]]

The evaluation parameters are : 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00       358
           1       1.00      1.00      1.00       642

    accuracy                           1.00      1000
   macro avg       1.00      1.00      1.00      1000
weighted avg       1.00      1.00      1.00      1000



In [29]:
RF_y_pred

array([1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0,

In [30]:
#CLASSIFICATION USING K-NEAREST NEIGHBOR
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)
knn = KNeighborsClassifier(n_neighbors=3)
KNN = knn.fit(X_train, y_train)
KNN_y_pred = KNN.predict(X)

accuracy = accuracy_score(y, KNN_y_pred)
print('Accuracy of K-nearest Neighbor classifier on test set:', accuracy)
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y, KNN_y_pred)
print('\nThe confusion Matrix is : \n',confusion_matrix)
from sklearn.metrics import classification_report
print('\nThe evaluation parameters are : \n',classification_report(y, KNN_y_pred))

Accuracy of K-nearest Neighbor classifier on test set: 0.803

The confusion Matrix is : 
 [[234 124]
 [ 73 569]]

The evaluation parameters are : 
               precision    recall  f1-score   support

           0       0.76      0.65      0.70       358
           1       0.82      0.89      0.85       642

    accuracy                           0.80      1000
   macro avg       0.79      0.77      0.78      1000
weighted avg       0.80      0.80      0.80      1000



In [31]:
KNN_y_pred

array([1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0,
       1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0,
       1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0,

In [32]:
#CLASSIFICATION USING DECISION TREE
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

from sklearn import metrics
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)
dt = DecisionTreeClassifier()
DT = dt.fit(X_train, y_train)
DT_y_pred = DT.predict(X)
print('Accuracy of Decision Tree classifier on test set: {:.2f}'.format(dt.score(X, y)))


from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y, DT_y_pred)
print('\nThe confusion Matrix is : \n',confusion_matrix)
from sklearn.metrics import classification_report
print('\nThe evaluation parameters are : \n',classification_report(y, DT_y_pred))

Accuracy of Decision Tree classifier on test set: 1.00

The confusion Matrix is : 
 [[358   0]
 [  0 642]]

The evaluation parameters are : 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00       358
           1       1.00      1.00      1.00       642

    accuracy                           1.00      1000
   macro avg       1.00      1.00      1.00      1000
weighted avg       1.00      1.00      1.00      1000



In [33]:
DT_y_pred

array([1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0,

###processed data-inferWith_parameter

In [69]:
data_dir="/content/drive/MyDrive/Colab/causal_inference-medical/student_performance/StudentsPerformance_processed.csv"
df=pd.read_csv(data_dir, encoding='utf-8')

In [70]:
df.drop(df.columns[[3]], axis=1,inplace=True)
df.gender = df.gender.map({"female":1,"male":0})
df.race = df.race.map({"group A":1,"group B":2,"group C":3,"group D":4,"group E":5})
df['student_performance'] = df['student_performance'].map({"none":1,"completed":0})
df.parental_level_of_education = df.parental_level_of_education.map({"associate's degree":1,"master's degree":2,"bachelor's degree":3,"some college":4,"high school":5,"some high school":6})
df.math_score
#df.test_preparation_course = df.test_preparation_course.map({"completed":1,"none":0})
df.to_csv('StudentsPerformance_processed',index=False,encoding='utf-8_sig')
df.head()

gender  race  parental_level_of_education  student_performance  math_score  \
0       1     2                            3                    1          72   
1       1     3                            4                    0          69   
2       1     2                            2                    1          90   
3       0     1                            1                    1          47   
4       0     3                            4                    1          76   

   reading_score  writing_score  
0           79.2             74  
1           99.0             88  
2          104.5             93  
3           62.7             44  
4           85.8             75

In [71]:
%%capture
!pip3 install pyro-ppl

In [72]:
import os
import pickle
from tqdm import tqdm
import torch
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import pyro
import pyro.distributions as dist
from torch import nn
import seaborn as sns
from pyro.nn import PyroModule
from sklearn.model_selection import train_test_split

ModuleNotFoundError: No module named 'pyro'

In [ ]:
# for CI testing
# smoke_test = ('CI' in os.environ)
pyro.enable_validation(True)
pyro.set_rng_seed(1)
pyro.enable_validation(True)

# setup
assert issubclass(PyroModule[nn.Linear], nn.Linear)
assert issubclass(PyroModule[nn.Linear], PyroModule)

###Create model

In [ ]:
def ScoresModelMSWS(G, R, PLE,           # 外生变量 (tensor 同长度)
                    RS=None, MS=None, WS=None):
    """
    与图匹配的结构方程 (所有 λ 都视为需要学习的权重)：

       MS =  λ1·G + λ2·R + λ3·PLE + ε_MS
       RS =  λ4·G + λ5·R + λ6·PLE + λ7·MS + ε_RS
       WS =  λ8·G + λ9·PLE + λ10·MS + λ11·RS + ε_WS
    噪声方差固定为 1，也可以再放 HalfNormal/InverseGamma 先验。
    """

    stdn = dist.Normal(0., 1.)

    # --- 所有权重 (λ) 与截距 (b) ----
    b_MS      = pyro.sample("b_MS",      stdn)
    lam_G_MS  = pyro.sample("lam_G_MS",  stdn)
    lam_R_MS  = pyro.sample("lam_R_MS",  stdn)
    lam_PLE_MS= pyro.sample("lam_PLE_MS",stdn)

    b_RS      = pyro.sample("b_RS",      stdn)
    lam_G_RS  = pyro.sample("lam_G_RS",  stdn)
    lam_R_RS  = pyro.sample("lam_R_RS",  stdn)
    lam_PLE_RS= pyro.sample("lam_PLE_RS",stdn)
    lam_MS_RS = pyro.sample("lam_MS_RS", stdn)

    b_WS      = pyro.sample("b_WS",      stdn)
    lam_G_WS  = pyro.sample("lam_G_WS",  stdn)
    lam_PLE_WS= pyro.sample("lam_PLE_WS",stdn)
    lam_MS_WS = pyro.sample("lam_MS_WS", stdn)
    lam_RS_WS = pyro.sample("lam_RS_WS", stdn)

    # ------------- 逐学生并行 -------------
    N = len(G)
    with pyro.plate("students", N):

        # ---- MS ----
        MS_mean = (b_MS +
                   lam_G_MS   * G +
                   lam_R_MS   * R +
                   lam_PLE_MS * PLE)
        MS = pyro.sample("MS", dist.Normal(MS_mean, 1.), obs=MS)

        # ---- RS ----
        RS_mean = (b_RS +
                   lam_G_RS   * G +
                   lam_R_RS   * R +
                   lam_PLE_RS * PLE +
                   lam_MS_RS  * MS)
        RS = pyro.sample("RS", dist.Normal(RS_mean, 1.), obs=RS)

        # ---- WS ----
        WS_mean = (b_WS +
                   lam_G_WS   * G +
                   lam_PLE_WS * PLE +
                   lam_MS_WS  * MS +
                   lam_RS_WS  * RS)
        WS = pyro.sample("WS", dist.Normal(WS_mean, 1.), obs=WS)

    return MS, WS            # 方便直接取值

In [ ]:
from tqdm.auto import tqdm
import pickle

# ----------- DataFrame 准备 ---------------
# 确保列顺序/命名与下面一致

# 把类别变量提前数值化，例如 0/1；哑变量可以取其中一列
G_tensor   = torch.tensor(df["gender"].values,  dtype=torch.float32)
R_tensor   = torch.tensor(df["race"].values,    dtype=torch.float32)
PLE_tensor = torch.tensor(df["parental_level_of_education"].values,
                          dtype=torch.float32)
RS_tensor  = torch.tensor(df["reading_score"].values, dtype=torch.float32)

# 用来存放后验均值
MS_post_mean, WS_post_mean = [], []

for i in tqdm(range(len(df))):

    # condition 里只固定读写分数；外生变量直接按标量传
    conditioned = pyro.condition(
        ScoresModelMSWS,
        data={"RS": RS_tensor[i]}      # 只观测 reading_score
    )

    posterior = pyro.infer.Importance(conditioned,
                                      num_samples=1_000)

    trace_emp = posterior.run(
        G  = G_tensor[i:i+1],          # 形状保持一致
        R  = R_tensor[i:i+1],
        PLE= PLE_tensor[i:i+1]
    )

    MS_marg = pyro.infer.EmpiricalMarginal(trace_emp, sites="MS")
    WS_marg = pyro.infer.EmpiricalMarginal(trace_emp, sites="WS")

    MS_post_mean.append(MS_marg.mean.item())
    WS_post_mean.append(WS_marg.mean.item())

# 收回 DataFrame
df["math_imputed"]    = MS_post_mean
df["writing_imputed"] = WS_post_mean

# 如有需要保存
with open("inferred_scores.pkl", "wb") as f:
    pickle.dump({"math": MS_post_mean,
                 "writing": WS_post_mean}, f)

In [ ]:
from pyro.infer import Predictive

def infer_all(df, num_samples=2_000):
    G   = torch.tensor(df["gender"].values,  dtype=torch.float32)
    R   = torch.tensor(df["race"].values,    dtype=torch.float32)
    PLE = torch.tensor(df["parental_level_of_education"].values,
                       dtype=torch.float32)
    RS_obs = torch.tensor(df["reading_score"].values, dtype=torch.float32)

    conditioned = pyro.condition(ScoresModelMSWS, data={"RS": RS_obs})

    predictive = Predictive(conditioned,
                            num_samples=num_samples,
                            return_sites=("MS", "WS"))

    samples = predictive(G=G, R=R, PLE=PLE)   # (S, N)
    df["math_imputed"]    = samples["MS"].mean(0).numpy()
    df["writing_imputed"] = samples["WS"].mean(0).numpy()
    return df

df_pred = infer_all(df)

In [94]:
import pandas as pd
data_dir="/content/drive/MyDrive/Colab/causal_inference-medical/student_performance/StudentsPerformance_processed_1.csv"
df=pd.read_csv(data_dir, encoding='utf-8')

In [95]:
df.drop(df.columns[[3]], axis=1,inplace=True)
df.gender = df.gender.map({"female":1,"male":0})
df.race = df.race.map({"group A":1,"group B":2,"group C":3,"group D":4,"group E":5})
df['student_performance'] = df['student_performance'].map({"none":1,"completed":0})
df.parental_level_of_education = df.parental_level_of_education.map({"associate's degree":1,"master's degree":2,"bachelor's degree":3,"some college":4,"high school":5,"some high school":6})
df.math_score
#df.test_preparation_course = df.test_preparation_course.map({"completed":1,"none":0})
df.to_csv('StudentsPerformance_processed',index=False,encoding='utf-8_sig')
df.head()

gender  race  parental_level_of_education  student_performance  math_score  \
0       1     2                            3                    1        89.2   
1       1     3                            4                    0        85.9   
2       1     2                            2                    1       109.0   
3       0     1                            1                    1        61.7   
4       0     3                            4                    1        93.6   

   reading_score  writing_score  
0           79.2          45.70  
1           99.0          53.40  
2          104.5          56.15  
3           62.7          29.20  
4           85.8          46.25

In [96]:
df_pred = df

In [97]:
y = df_pred.iloc[:, 3]

In [98]:
X = pd.concat([df_pred.iloc[:, :2], df_pred.iloc[:, 3:]], axis=1)

In [99]:
X

gender  race  student_performance  math_score  reading_score  \
0         1     2                    1        89.2           79.2   
1         1     3                    0        85.9           99.0   
2         1     2                    1       109.0          104.5   
3         0     1                    1        61.7           62.7   
4         0     3                    1        93.6           85.8   
..      ...   ...                  ...         ...            ...   
995       1     5                    0        98.0          108.9   
996       0     3                    1        72.0           60.5   
997       1     3                    0        69.0           78.1   
998       1     4                    0        78.0           85.8   
999       1     4                    1        87.0           94.6   

     writing_score  
0            45.70  
1            53.40  
2            56.15  
3            29.20  
4            46.25  
..             ...  
995          57.25  
996          35.25  
997          40.75  
998          47.35  
999          52.30  

[1000 rows x 6 columns]

###ML test

In [100]:
#CLASSIFICATION USING SVM
from sklearn import svm
from sklearn.model_selection import train_test_split

from sklearn import metrics
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)
clf = svm.SVC()
SVM = clf.fit(X_train, y_train)

SVM_y_pred_CIMW = SVM.predict(X)
print('Accuracy of SVM classifier on test set: {:.2f}'.format(clf.score(X, y)))
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y, SVM_y_pred)
print('\nThe confusion Matrix is : \n',confusion_matrix)
from sklearn.metrics import classification_report
print('\nThe evaluation parameters are : \n',classification_report(y, SVM_y_pred))

Accuracy of SVM classifier on test set: 0.66

The confusion Matrix is : 
 [[ 89 269]
 [ 46 596]]

The evaluation parameters are : 
               precision    recall  f1-score   support

           0       0.66      0.25      0.36       358
           1       0.69      0.93      0.79       642

    accuracy                           0.69      1000
   macro avg       0.67      0.59      0.58      1000
weighted avg       0.68      0.69      0.64      1000



In [101]:
SVM_y_pred_CIMW

array([1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [102]:
#CLASSIFICATION USING NAIVE BAYES
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split

from sklearn import metrics
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)
clf = GaussianNB()
NB = clf.fit(X_train, y_train)

NB_y_pred_CIMW = NB.predict(X)
print('Accuracy of Naive Bayes classifier on test set: {:.2f}'.format(clf.score(X, y)))
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y, NB_y_pred)
print('\nThe confusion Matrix is : \n',confusion_matrix)
from sklearn.metrics import classification_report
print('\nThe evaluation parameters are : \n',classification_report(y, NB_y_pred))

Accuracy of Naive Bayes classifier on test set: 1.00

The confusion Matrix is : 
 [[358   0]
 [  0 642]]

The evaluation parameters are : 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00       358
           1       1.00      1.00      1.00       642

    accuracy                           1.00      1000
   macro avg       1.00      1.00      1.00      1000
weighted avg       1.00      1.00      1.00      1000



In [103]:
NB_y_pred_CIMW

array([1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0,

In [104]:
#CLASSIFICATION USING RANDOM FOREST
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

from sklearn import metrics
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)
clf = RandomForestClassifier()
RF = clf.fit(X_train, y_train)

RF_y_pred_CIMW = RF.predict(X)
print('Accuracy of Random Forest classifier on test set: {:.2f}'.format(clf.score(X, y)))
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y, RF_y_pred)
print('\nThe confusion Matrix is : \n',confusion_matrix)
from sklearn.metrics import classification_report
print('\nThe evaluation parameters are : \n',classification_report(y, RF_y_pred))

Accuracy of Random Forest classifier on test set: 1.00

The confusion Matrix is : 
 [[358   0]
 [  0 642]]

The evaluation parameters are : 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00       358
           1       1.00      1.00      1.00       642

    accuracy                           1.00      1000
   macro avg       1.00      1.00      1.00      1000
weighted avg       1.00      1.00      1.00      1000



In [105]:
RF_y_pred_CIMW

array([1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0,

In [106]:
#CLASSIFICATION USING K-NEAREST NEIGHBOR
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)
knn = KNeighborsClassifier(n_neighbors=3)
KNN = knn.fit(X_train, y_train)
KNN_y_pred_CIMW = KNN.predict(X)

accuracy = accuracy_score(y, KNN_y_pred)
print('Accuracy of K-nearest Neighbor classifier on test set:', accuracy)
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y, KNN_y_pred)
print('\nThe confusion Matrix is : \n',confusion_matrix)
from sklearn.metrics import classification_report
print('\nThe evaluation parameters are : \n',classification_report(y, KNN_y_pred))

Accuracy of K-nearest Neighbor classifier on test set: 0.803

The confusion Matrix is : 
 [[234 124]
 [ 73 569]]

The evaluation parameters are : 
               precision    recall  f1-score   support

           0       0.76      0.65      0.70       358
           1       0.82      0.89      0.85       642

    accuracy                           0.80      1000
   macro avg       0.79      0.77      0.78      1000
weighted avg       0.80      0.80      0.80      1000



In [107]:
KNN_y_pred_CIMW

array([1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1,
       1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1,
       1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1,

In [108]:
#CLASSIFICATION USING DECISION TREE
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

from sklearn import metrics
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)
dt = DecisionTreeClassifier()
DT = dt.fit(X_train, y_train)
DT_y_pred_CIMW = DT.predict(X)
print('Accuracy of Decision Tree classifier on test set: {:.2f}'.format(dt.score(X, y)))


from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y, DT_y_pred)
print('\nThe confusion Matrix is : \n',confusion_matrix)
from sklearn.metrics import classification_report
print('\nThe evaluation parameters are : \n',classification_report(y, DT_y_pred))

Accuracy of Decision Tree classifier on test set: 1.00

The confusion Matrix is : 
 [[358   0]
 [  0 642]]

The evaluation parameters are : 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00       358
           1       1.00      1.00      1.00       642

    accuracy                           1.00      1000
   macro avg       1.00      1.00      1.00      1000
weighted avg       1.00      1.00      1.00      1000



In [109]:
DT_y_pred_CIMW

array([1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0,