In [ ]:
import pandas as pd
data_dir="/content/drive/MyDrive/Colab/causal_inference-medical/student_performance/StudentsPerformance.csv"
df=pd.read_csv(data_dir, encoding='utf-8')

In [ ]:
df.head()

gender     race parental_level_of_education         lunch  \
0  female  group B           bachelor's degree      standard   
1  female  group C                some college      standard   
2  female  group B             master's degree      standard   
3    male  group A          associate's degree  free/reduced   
4    male  group C                some college      standard   

  student_performance  math_score  reading_score  writing_score  
0                none          72             72             74  
1           completed          69             90             88  
2                none          90             95             93  
3                none          47             57             44  
4                none          76             78             75

In [ ]:
df.drop(df.columns[[3]], axis=1,inplace=True)
df.gender = df.gender.map({"female":1,"male":0})
df.race = df.race.map({"group A":1,"group B":2,"group C":3,"group D":4,"group E":5})
df['student_performance'] = df['student_performance'].map({"none":1,"completed":0})
df.parental_level_of_education = df.parental_level_of_education.map({"associate's degree":1,"master's degree":2,"bachelor's degree":3,"some college":4,"high school":5,"some high school":6})
df.math_score
#df.test_preparation_course = df.test_preparation_course.map({"completed":1,"none":0})
df.to_csv('StudentsPerformance_processed',index=False,encoding='utf-8_sig')
df.head()

gender  race  parental_level_of_education  student_performance  math_score  \
0       1     2                            3                    1          72   
1       1     3                            4                    0          69   
2       1     2                            2                    1          90   
3       0     1                            1                    1          47   
4       0     3                            4                    1          76   

   reading_score  writing_score  
0             72             74  
1             90             88  
2             95             93  
3             57             44  
4             78             75

### ML Without CI

In [ ]:
df.columns = ['gender', 'race', 'parental_level_of_education', 'student_performance', 'math_score', 'reading_score', 'writing_score']
df

gender  race  parental_level_of_education  student_performance  \
0         1     2                            3                    1   
1         1     3                            4                    0   
2         1     2                            2                    1   
3         0     1                            1                    1   
4         0     3                            4                    1   
..      ...   ...                          ...                  ...   
995       1     5                            2                    0   
996       0     3                            5                    1   
997       1     3                            5                    0   
998       1     4                            4                    0   
999       1     4                            4                    1   

     math_score  reading_score  writing_score  
0            72             72             74  
1            69             90             88  
2            90             95             93  
3            47             57             44  
4            76             78             75  
..          ...            ...            ...  
995          88             99             95  
996          62             55             55  
997          59             71             65  
998          68             78             77  
999          77             86             86  

[1000 rows x 7 columns]

In [ ]:
y = df.iloc[:, 3]

In [ ]:
X = pd.concat([df.iloc[:, :2], df.iloc[:, 3:]], axis=1)

In [ ]:
#CLASSIFICATION USING SVM
from sklearn import svm
from sklearn.model_selection import train_test_split

from sklearn import metrics
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)
clf = svm.SVC()
SVM = clf.fit(X_train, y_train)

SVM_y_pred = SVM.predict(X)
print('Accuracy of SVM classifier on test set: {:.2f}'.format(clf.score(X, y)))
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y, SVM_y_pred)
print('\nThe confusion Matrix is : \n',confusion_matrix)
from sklearn.metrics import classification_report
print('\nThe evaluation parameters are : \n',classification_report(y, SVM_y_pred))

Accuracy of SVM classifier on test set: 0.69

The confusion Matrix is : 
 [[ 89 269]
 [ 46 596]]

The evaluation parameters are : 
               precision    recall  f1-score   support

           0       0.66      0.25      0.36       358
           1       0.69      0.93      0.79       642

    accuracy                           0.69      1000
   macro avg       0.67      0.59      0.58      1000
weighted avg       0.68      0.69      0.64      1000



In [ ]:
SVM_y_pred

array([1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [ ]:
import numpy as np
eff_withoutCI_SVM = np.mean(SVM_y_pred == 1)
print(eff_withoutCI_SVM)

0.865


In [ ]:
#CLASSIFICATION USING NAIVE BAYES
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split

from sklearn import metrics
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)
clf = GaussianNB()
NB = clf.fit(X_train, y_train)

NB_y_pred = NB.predict(X)
print('Accuracy of Naive Bayes classifier on test set: {:.2f}'.format(clf.score(X, y)))
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y, NB_y_pred)
print('\nThe confusion Matrix is : \n',confusion_matrix)
from sklearn.metrics import classification_report
print('\nThe evaluation parameters are : \n',classification_report(y, NB_y_pred))

Accuracy of Naive Bayes classifier on test set: 1.00

The confusion Matrix is : 
 [[358   0]
 [  0 642]]

The evaluation parameters are : 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00       358
           1       1.00      1.00      1.00       642

    accuracy                           1.00      1000
   macro avg       1.00      1.00      1.00      1000
weighted avg       1.00      1.00      1.00      1000



In [ ]:
NB_y_pred

array([1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0,

In [ ]:
#CLASSIFICATION USING RANDOM FOREST
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

from sklearn import metrics
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)
clf = RandomForestClassifier()
RF = clf.fit(X_train, y_train)

RF_y_pred = RF.predict(X)
print('Accuracy of Random Forest classifier on test set: {:.2f}'.format(clf.score(X, y)))
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y, RF_y_pred)
print('\nThe confusion Matrix is : \n',confusion_matrix)
from sklearn.metrics import classification_report
print('\nThe evaluation parameters are : \n',classification_report(y, RF_y_pred))

Accuracy of Random Forest classifier on test set: 1.00

The confusion Matrix is : 
 [[358   0]
 [  0 642]]

The evaluation parameters are : 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00       358
           1       1.00      1.00      1.00       642

    accuracy                           1.00      1000
   macro avg       1.00      1.00      1.00      1000
weighted avg       1.00      1.00      1.00      1000



In [ ]:
RF_y_pred

array([1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0,

In [ ]:
#CLASSIFICATION USING K-NEAREST NEIGHBOR
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)
knn = KNeighborsClassifier(n_neighbors=3)
KNN = knn.fit(X_train, y_train)
KNN_y_pred = KNN.predict(X)

accuracy = accuracy_score(y, KNN_y_pred)
print('Accuracy of K-nearest Neighbor classifier on test set:', accuracy)
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y, KNN_y_pred)
print('\nThe confusion Matrix is : \n',confusion_matrix)
from sklearn.metrics import classification_report
print('\nThe evaluation parameters are : \n',classification_report(y, KNN_y_pred))

Accuracy of K-nearest Neighbor classifier on test set: 0.803

The confusion Matrix is : 
 [[234 124]
 [ 73 569]]

The evaluation parameters are : 
               precision    recall  f1-score   support

           0       0.76      0.65      0.70       358
           1       0.82      0.89      0.85       642

    accuracy                           0.80      1000
   macro avg       0.79      0.77      0.78      1000
weighted avg       0.80      0.80      0.80      1000



In [ ]:
KNN_y_pred

array([1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0,
       1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0,
       1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0,

In [ ]:
#CLASSIFICATION USING DECISION TREE
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

from sklearn import metrics
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)
dt = DecisionTreeClassifier()
DT = dt.fit(X_train, y_train)
DT_y_pred = DT.predict(X)
print('Accuracy of Decision Tree classifier on test set: {:.2f}'.format(dt.score(X, y)))


from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y, DT_y_pred)
print('\nThe confusion Matrix is : \n',confusion_matrix)
from sklearn.metrics import classification_report
print('\nThe evaluation parameters are : \n',classification_report(y, DT_y_pred))

Accuracy of Decision Tree classifier on test set: 1.00

The confusion Matrix is : 
 [[358   0]
 [  0 642]]

The evaluation parameters are : 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00       358
           1       1.00      1.00      1.00       642

    accuracy                           1.00      1000
   macro avg       1.00      1.00      1.00      1000
weighted avg       1.00      1.00      1.00      1000



In [ ]:
DT_y_pred

array([1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0,

###processed data-inferWith_parameter

In [ ]:
data_dir="/content/drive/MyDrive/Colab/causal_inference-medical/student_performance/StudentsPerformance_processed.csv"
df=pd.read_csv(data_dir, encoding='utf-8')

In [ ]:
df.drop(df.columns[[3]], axis=1,inplace=True)
df.gender = df.gender.map({"female":1,"male":0})
df.race = df.race.map({"group A":1,"group B":2,"group C":3,"group D":4,"group E":5})
#df['student_performance'] = df['student_performance'].map({"none":1,"completed":0})
df.parental_level_of_education = df.parental_level_of_education.map({"associate's degree":1,"master's degree":2,"bachelor's degree":3,"some college":4,"high school":5,"some high school":6})
df.math_score
#df.test_preparation_course = df.test_preparation_course.map({"completed":1,"none":0})
df.to_csv('StudentsPerformance_processed',index=False,encoding='utf-8_sig')
df.head()

gender  race  parental_level_of_education student_performance  math_score  \
0       1     2                            3                none          72   
1       1     3                            4           completed          69   
2       1     2                            2                none          90   
3       0     1                            1                none          47   
4       0     3                            4                none          76   

   reading_score  writing_score  
0           79.2             74  
1           99.0             88  
2          104.5             93  
3           62.7             44  
4           85.8             75

In [ ]:
%%capture
!pip3 install pyro-ppl

In [ ]:
import os
import pickle
from tqdm import tqdm
import torch
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import pyro
import pyro.distributions as dist
from torch import nn
import seaborn as sns
from pyro.nn import PyroModule
from sklearn.model_selection import train_test_split

In [ ]:
# for CI testing
# smoke_test = ('CI' in os.environ)
pyro.enable_validation(True)
pyro.set_rng_seed(1)
pyro.enable_validation(True)

# setup
assert issubclass(PyroModule[nn.Linear], nn.Linear)
assert issubclass(PyroModule[nn.Linear], PyroModule)

###Create model

In [ ]:
def StudentScoresModel(gender, race, ple,     # 外生变量 (scalars)
                       RS=None, MS=None, WS=None):    # 可以任选地观测
    """
    方程：
      MS ~ N(-11.767*G + 0.935*R , 1)
      RS ~ N( 7.009*G + 1.672*R + 1.131*MS - 1.123*PLE , 1)
      WS ~ N( 5.277*G + 0.259*MS + 0.724*RS - 0.308*PLE , 1)
    系数固定，噪声方差取 1，如需学习可改成随机。
    """
    # ── 1. math_score ─────────────────────────────
    MS_mean = -11.767 * gender + 0.935 * race
    MS = pyro.sample("MS", dist.Normal(MS_mean, 1.0), obs=MS)

    # ── 2. reading_score ─────────────────────────
    RS_mean = (7.009 * gender +
               1.672 * race   +
               1.131 * MS     -
               1.123 * ple)
    RS = pyro.sample("RS", dist.Normal(RS_mean, 1.0), obs=RS)

    # ── 3. writing_score ─────────────────────────
    WS_mean = (5.277 * gender +
               0.259 * MS     +
               0.724 * RS     -
               0.308 * ple)
    WS = pyro.sample("WS", dist.Normal(WS_mean, 1.0), obs=WS)

    return MS, WS            # 方便 direct call 时取值

In [ ]:
def infer_single(row, num_samples=1_000):
    """
    给定一行 DataFrame，只观测 reading_score，
    返回 math_score、writing_score 的后验样本均值
    """
    # scalar tensors
    G   = torch.tensor(row["gender"],  dtype=torch.float32)
    R   = torch.tensor(row["race"],    dtype=torch.float32)
    PLE = torch.tensor(row["parental_level_of_education"],
                       dtype=torch.float32)
    RS_obs = torch.tensor(row["reading_score"], dtype=torch.float32)

    # 用 condition 固定 RS
    conditioned_model = pyro.condition(
        StudentScoresModel,
        data={"RS": RS_obs}
    )

    # Importance 采样 —— 与您原来的写法一致
    imp = pyro.infer.Importance(conditioned_model,
                                num_samples=num_samples)

    posterior_traces = imp.run(gender=G, race=R, ple=PLE)

    # 抽取后验
    MS_marg = pyro.infer.EmpiricalMarginal(posterior_traces, sites="MS")
    WS_marg = pyro.infer.EmpiricalMarginal(posterior_traces, sites="WS")

    return MS_marg.mean.item(), WS_marg.mean.item()

In [ ]:
math_pred, writing_pred = [], []

for _, row in tqdm(df.iterrows(), total=len(df)):
    m, w = infer_single(row, num_samples=1_000)
    math_pred.append(m)
    writing_pred.append(w)

df["math_score"]    = math_pred
df["writing_score"] = writing_pred

100%|██████████| 1000/1000 [32:28<00:00,  1.95s/it]


In [ ]:
from pyro.infer import Predictive

def infer_batch(dataframe, num_samples=1_000):
    G   = torch.tensor(dataframe["gender"].values,  dtype=torch.float32)
    R   = torch.tensor(dataframe["race"].values,    dtype=torch.float32)
    PLE = torch.tensor(dataframe["parental_level_of_education"].values,
                       dtype=torch.float32)
    RS_obs = torch.tensor(dataframe["reading_score"].values,
                          dtype=torch.float32)

    # 条件化：仅给定 RS
    conditioned = pyro.condition(
        StudentScoresModel,
        data={"RS": RS_obs}
    )

    predictive = Predictive(conditioned,
                            num_samples=num_samples,
                            return_sites=("MS", "WS"))

    samples = predictive(gender=G, race=R, ple=PLE)  # dict 里含 (num_samples, N)

    # 取均值作为点估计
    math_mean    = samples["MS"].mean(0).numpy()
    writing_mean = samples["WS"].mean(0).numpy()

    dataframe = dataframe.copy()
    dataframe["math_imputed"]    = math_mean
    dataframe["writing_imputed"] = writing_mean
    return dataframe, samples    # 如需全套样本可同时返回

In [ ]:
df_pred, full_samples = infer_batch(df, num_samples=2_000)
df_pred.head()

gender  race  parental_level_of_education student_performance  math_score  \
0       1     2                            3                none   -6.310011   
1       1     3                            4           completed   -5.997540   
2       1     2                            2                none   -6.675563   
3       0     1                            1                none    4.219141   
4       0     3                            4                none    5.989233   

   reading_score  writing_score  math_imputed  writing_imputed  
0           79.2      58.228214     -9.893186        59.147026  
1           99.0      74.834969     -8.932858        73.389748  
2          104.5      77.967735     -9.862827        77.735390  
3           62.7      45.931465      0.969854        45.359531  
4           85.8      61.633850      2.826250        61.617573

In [ ]:
df_pred['student_performance'] = df_pred['student_performance'].map({"none":1,"completed":0})

In [ ]:
y = df_pred.iloc[:, 3]

In [ ]:
X = pd.concat([df_pred.iloc[:, :2], df_pred.iloc[:, 3:]], axis=1)

In [ ]:
X

gender  race  student_performance  math_score  reading_score  \
0         1     2                    1   -6.310011           79.2   
1         1     3                    0   -5.997540           99.0   
2         1     2                    1   -6.675563          104.5   
3         0     1                    1    4.219141           62.7   
4         0     3                    1    5.989233           85.8   
..      ...   ...                  ...         ...            ...   
995       1     5                    0   -3.553827          108.9   
996       0     3                    1    5.635768           60.5   
997       1     3                    0   -5.925522           78.1   
998       1     4                    0   -4.458898           85.8   
999       1     4                    1   -5.149107           94.6   

     writing_score  math_imputed  writing_imputed  
0        58.228214     -9.893186        59.147026  
1        74.834969     -8.932858        73.389748  
2        77.967735     -9.862827        77.735390  
3        45.931465      0.969854        45.359531  
4        61.633850      2.826250        61.617573  
..             ...           ...              ...  
995      83.602066     -7.099399        81.683586  
996      45.406467      2.775321        42.996078  
997      59.124401     -8.967344        57.941952  
998      66.114189     -8.018496        64.099434  
999      72.075439     -8.031010        70.420029  

[1000 rows x 8 columns]

###ML test

In [ ]:
#CLASSIFICATION USING SVM
from sklearn import svm
from sklearn.model_selection import train_test_split

from sklearn import metrics
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)
clf = svm.SVC()
SVM = clf.fit(X_train, y_train)

SVM_y_pred_CIDW = SVM.predict(X)
print('Accuracy of SVM classifier on test set: {:.2f}'.format(clf.score(X, y)))
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y, SVM_y_pred)
print('\nThe confusion Matrix is : \n',confusion_matrix)
from sklearn.metrics import classification_report
print('\nThe evaluation parameters are : \n',classification_report(y, SVM_y_pred))

Accuracy of SVM classifier on test set: 0.64

The confusion Matrix is : 
 [[ 89 269]
 [ 46 596]]

The evaluation parameters are : 
               precision    recall  f1-score   support

           0       0.66      0.25      0.36       358
           1       0.69      0.93      0.79       642

    accuracy                           0.69      1000
   macro avg       0.67      0.59      0.58      1000
weighted avg       0.68      0.69      0.64      1000



In [ ]:
SVM_y_pred_CIDW

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [ ]:
#CLASSIFICATION USING NAIVE BAYES
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split

from sklearn import metrics
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)
clf = GaussianNB()
NB = clf.fit(X_train, y_train)

NB_y_pred_CIDW = NB.predict(X)
print('Accuracy of Naive Bayes classifier on test set: {:.2f}'.format(clf.score(X, y)))
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y, NB_y_pred)
print('\nThe confusion Matrix is : \n',confusion_matrix)
from sklearn.metrics import classification_report
print('\nThe evaluation parameters are : \n',classification_report(y, NB_y_pred))

Accuracy of Naive Bayes classifier on test set: 1.00

The confusion Matrix is : 
 [[358   0]
 [  0 642]]

The evaluation parameters are : 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00       358
           1       1.00      1.00      1.00       642

    accuracy                           1.00      1000
   macro avg       1.00      1.00      1.00      1000
weighted avg       1.00      1.00      1.00      1000



In [ ]:
NB_y_pred_CIDW

array([1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0,

In [ ]:
#CLASSIFICATION USING RANDOM FOREST
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

from sklearn import metrics
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)
clf = RandomForestClassifier()
RF = clf.fit(X_train, y_train)

RF_y_pred_CIDW = RF.predict(X)
print('Accuracy of Random Forest classifier on test set: {:.2f}'.format(clf.score(X, y)))
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y, RF_y_pred)
print('\nThe confusion Matrix is : \n',confusion_matrix)
from sklearn.metrics import classification_report
print('\nThe evaluation parameters are : \n',classification_report(y, RF_y_pred))

Accuracy of Random Forest classifier on test set: 1.00

The confusion Matrix is : 
 [[358   0]
 [  0 642]]

The evaluation parameters are : 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00       358
           1       1.00      1.00      1.00       642

    accuracy                           1.00      1000
   macro avg       1.00      1.00      1.00      1000
weighted avg       1.00      1.00      1.00      1000



In [ ]:
RF_y_pred_CIDW

array([1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0,

In [ ]:
#CLASSIFICATION USING K-NEAREST NEIGHBOR
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)
knn = KNeighborsClassifier(n_neighbors=3)
KNN = knn.fit(X_train, y_train)
KNN_y_pred_CIDW = KNN.predict(X)

accuracy = accuracy_score(y, KNN_y_pred)
print('Accuracy of K-nearest Neighbor classifier on test set:', accuracy)
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y, KNN_y_pred)
print('\nThe confusion Matrix is : \n',confusion_matrix)
from sklearn.metrics import classification_report
print('\nThe evaluation parameters are : \n',classification_report(y, KNN_y_pred))

Accuracy of K-nearest Neighbor classifier on test set: 0.803

The confusion Matrix is : 
 [[234 124]
 [ 73 569]]

The evaluation parameters are : 
               precision    recall  f1-score   support

           0       0.76      0.65      0.70       358
           1       0.82      0.89      0.85       642

    accuracy                           0.80      1000
   macro avg       0.79      0.77      0.78      1000
weighted avg       0.80      0.80      0.80      1000



In [ ]:
KNN_y_pred_CIDW

array([1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0,

In [ ]:
#CLASSIFICATION USING DECISION TREE
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

from sklearn import metrics
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)
dt = DecisionTreeClassifier()
DT = dt.fit(X_train, y_train)
DT_y_pred_CIDW = DT.predict(X)
print('Accuracy of Decision Tree classifier on test set: {:.2f}'.format(dt.score(X, y)))


from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y, DT_y_pred)
print('\nThe confusion Matrix is : \n',confusion_matrix)
from sklearn.metrics import classification_report
print('\nThe evaluation parameters are : \n',classification_report(y, DT_y_pred))

Accuracy of Decision Tree classifier on test set: 1.00

The confusion Matrix is : 
 [[358   0]
 [  0 642]]

The evaluation parameters are : 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00       358
           1       1.00      1.00      1.00       642

    accuracy                           1.00      1000
   macro avg       1.00      1.00      1.00      1000
weighted avg       1.00      1.00      1.00      1000



In [ ]:
DT_y_pred_CIDW

array([1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0,